### ISSUE TITLE
Tactic state

### ISSUE THREAD

**Issue by lambdaofgod** [leanprover-community/lean4-mode#62]
Does lean4 mode have something like this tactic state pane [here](https://youtu.be/POHVMMG7pqE)?

**Comment by sanchace** [comment]
Yes, by default it's bound to `C-c C-i` and `C-c TAB`.  In general, you can use `C-h m` in any buffer to see the docs for your emacs modes for that buffer; in there, you'll see the line "`C-c TAB`  lean4-toggle-info".  If I recall correctly, the "tactic state pane" is officially called the "lean infoview panel".

**Comment by lambdaofgod** [comment]
Ok, I was confused because it didn't work at first.
